### ISSUE TITLE
Proposal to Add PeerDependencies to Project

### ISSUE THREAD

**Issue by recepkefelii** [rubiklabs/nestjs-netgsm-client#2]
I wanted to suggest adding a PeerDependencies section to the project's package.json file. Currently this section is missing and i believe its important to include it

PeerDependencies are used to specify which packages your project expects to be used alongside it this helps to prevent version conflicts and ensures that the required packages are installed before your project is used

By adding a PeerDependencies section to the project it will make it easier for users to understand which dependencies are necessary for the project to function correctly this can help prevent potential issues and make the development process smoother

Please let me know if you have any questions or concerns about adding an PeerDependencies section to the package.json file

source: [Article](https://dev.to/nestjs/publishing-nestjs-packages-with-npm-21fm)
John Biundo nestjs core team

**Comment by ipeq32** [comment]
Thank you for your suggestions. We had already discussed this topic and were undecided whether to add it or not. 
We are honored that you have expressed your thoughts.

We wish you a nice day.
